<?php

namespace AppBundle\Repository;

/**
 * CouleurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CouleurRepository extends \Doctrine\ORM\EntityRepository
{
}
