<?php

namespace AppBundle\Repository;

/**
 * EtatVeloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtatVeloRepository extends \Doctrine\ORM\EntityRepository
{
}
