<?php

namespace AppBundle\Repository;

/**
 * LocTelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocTelRepository extends \Doctrine\ORM\EntityRepository
{
}
