<?php

namespace AppBundle\Repository;

/**
 * PhotoVeloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoVeloRepository extends \Doctrine\ORM\EntityRepository
{
}
