<?php

namespace AppBundle\Repository;

/**
 * TypeVeloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeVeloRepository extends \Doctrine\ORM\EntityRepository
{
}
