<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VeloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VeloRepository extends EntityRepository
{

    public function searchAnnonces()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT v.coutPts, v.latitude, v.longitude, m.avatarImage, t.type, p.image, m.prenom
            FROM AppBundle:Velo v
                JOIN AppBundle:Membre m WHERE v.proprio = m.id
                    JOIN AppBundle:TypeVelo t WHERE v.typeVelo = t.id
                        JOIN AppBundle:PhotoVelo p WHERE v.id = p.velo'
            )
            ->getResult();

    }
}
